### ISSUE TITLE
warning messages when running pconsC4 (critical or not)?

### ISSUE THREAD

**Issue by curiousa** [ElofssonLab/PconsC4#4]
Hello there,

I get warning messages when running pconsC4, whereas during installation of the pconsC4 package and its dependencies I had no compilation errors. I was wondering is the warning messages I list below are going to affect the outcome of the method, or should I just ignore those?

Thanks,
Alina

-bash-4.2$ python
Python 3.6.8 |Anaconda custom (64-bit)| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pconsc4
Using TensorFlow backend.
>>> model = pconsc4.get_pconsc4()
WARNING:tensorflow:From /ifs/scratch/c2b2/bh_lab/aps2174/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-04-30 14:30:44.794436: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2294305000 Hz
2019-04-30 14:30:44.794686: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x560dc45b9070 executing computations on platform Host. Devices:
2019-04-30 14:30:44.794827: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /ifs/scratch/c2b2/bh_lab/aps2174/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
/ifs/scratch/c2b2/bh_lab/aps2174/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
>>> UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  File "<stdin>", line 1
    UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
                           ^
SyntaxError: invalid syntax
>>>   warnings.warn('No training configuration found in save file: '
  File "<stdin>", line 1
    warnings.warn('No training configuration found in save file: '
    ^
IndentationError: unexpected indent
>>> pred_1 = pconsc4.predict(model, 'DIPs.fasta')
>>> import matplotlib.pyplot as plt 
>>> plt.imshow(pred_1['cmap'])
<matplotlib.image.AxesImage object at 0x7f37489b6390>
>>> plt.savefig('fig.png')

**Comment by Dapid** [comment]
The `UserWarning: No training configuration found in save file: the model was not compiled. ` are harmless. It is because we are loading a Keras model, but since we are not predicting, we don't need compilation.
