### ISSUE TITLE
Segmentation Fault but .fasta file has no line wrapping

### ISSUE THREAD

**Issue by CuongVoThanh** [ElofssonLab/PconsC4#9]
Hi Author,

I tried to run the code with .fasta file input. I checked that the .fasta file has no line wrapping but when I sill got the segmentation fault bug. I have spent a lot of effort but I still have yet had a solution.

Here is my .fasta file  (I have changed to .txt because github doesnot allow to attach .fasta file)
[P78527.txt](https://github.com/ElofssonLab/PconsC4/files/6714529/P78527.txt)

Could you have a check the problem?
Thanks you.

**Comment by Dapid** [comment]
That is a single sequence, you need to pass a multiple sequence alignment. You can use Jackhammer and reformat Stockholm to A3M using https://pypi.org/project/stockholm_reformat/
